# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_descrition',
            new_name='game_description',
        ),
    ]
