# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 16:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0002_auto_20161229_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile Picture', models.FileField(upload_to='')),
                ('detail', models.CharField(max_length=250, null=True)),
                ('dob', models.DateField(null=True)),
                ('level', models.IntegerField(choices=[(0, 'Beginner'), (1, 'Amateur'), (2, 'Professional'), (3, 'Expert')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
