# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(choices=[(0, 'Beginner'), (1, 'Amateur'), (2, 'Professional'), (3, 'Expert')], default=0),
        ),
    ]
