# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_auto_20170104_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Profile Picture',
            new_name='Profile_Picture',
        ),
    ]
